### PR TITLE
Update en_us.json

### PR DESCRIPTION
**Pull request by Howie0715**

### CODE REVIEW

**Comment by Tom-The-Geek** [comment]
If you want to translate the minigame to another language, please add a new file named for the locale (eg. `es_es.json` for spanish) rather than replacing the US English versions :smile:

**Comment by Restioson** [comment]
According to [stackoverflow](https://stackoverflow.com/questions/4892372/language-codes-for-simplified-chinese-and-traditional-chinese):

> There are several countries where Chinese is the main written language. The major difference between them is whether they use simplified or traditional characters, but there are also minor regional differences (in vocabulary, etc). The standard way to distinguish these would be with a country code, e.g. zh_CN for mainland China, zh_SG for Singapore, zh_TW for Taiwan, or zh_HK for Hong Kong.

So, if the translation here is Chinese used in mainland China, the file would be `zh_cn.json`, if it were Singaporean, `zh_sg.json`, if it were from Hong Kong it would be `zh_hk.json`, and if it were Taiwanese it would be `zh_tw.json`.

**Comment by Howie0715** [comment]
Sorry. I'm nooooob Orz

**Comment by Restioson** [comment]
No problem. We would be happy to review the pull request if it were submitted with the correct filename, and thank you for your time :smile:

**Pull request closed without merging**
