### PR TITLE
Add roadway map

### PR DESCRIPTION
**Pull request by yitzy299**
image
image
image
image
image

### CODE REVIEW

**Comment by Restioson** [comment]
Looks awesome! Regions all set up I take it?

**Comment by yitzy299** [comment]
> Looks awesome! Regions all set up I take it?

I believe so, although it is my first map contribution so maybe check on the build server to make sure I've done everything how you want it

**Comment by yitzy299** [comment]
Also, I forgot to add something, let me commit that

**Comment by yitzy299** [comment]
image
I fixed the hole there

**Comment by Gegy** [comment]
Thank you!

**Pull request merged**
